version: '3'

services:
  postgresql:
    image: postgres:9.6-alpine
    container_name: 'postgresql-db'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql-db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgresql-db-data:
    driver: local